# Generated by Django 5.1.6 on 2025-02-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
