# Generated by Django 5.1.6 on 2025-02-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
